In [2]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.9348e-19, 1.6631e+22, 2.0283e-19],
        [1.8990e+28, 1.8177e+31, 1.7418e+28],
        [7.1463e+22, 7.6724e+34, 4.4646e+30],
        [7.5569e+28, 1.0579e+21, 1.2120e+25],
        [7.2444e+22, 6.6532e-33, 1.3563e-19]])


In [3]:
x = torch.rand(5, 3)
print(x)


tensor([[0.4810, 0.2170, 0.7266],
        [0.7882, 0.6576, 0.7462],
        [0.5876, 0.4283, 0.6218],
        [0.1446, 0.0647, 0.3460],
        [0.9513, 0.4966, 0.7120]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)


tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x)

print(x.size())
print(x.shape)

# 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0254, -1.2514,  0.2989],
        [ 3.7436, -0.5737,  0.2813],
        [ 0.5093, -0.4422, -0.1360],
        [ 1.0209, -1.0003,  0.5632],
        [-1.1061,  0.5982,  1.0232]])
torch.Size([5, 3])
torch.Size([5, 3])


还有很多函数可以创建Tensor，去翻翻官方API就知道了，下表给了一些常用的作参考。

函数	           
Tensor(*sizes): 基础构造函数

tensor(data,): 类似np.array的构造函数

ones(*sizes): 全1Tensor


zeros(*sizes): 全0Tensor

eye(*sizes): 对角线为1，其他为0

arange(s,e,step):	从s到e，步长为step

linspace(s,e,steps):	从s到e，均匀切分成steps份

rand/randn(*sizes):	均匀/标准分布

normal(mean,std)/uniform(from,to): 正态分布/均匀分布

randperm(m): 随机排列

这些创建方法都可以在创建的时候指定数据类型dtype和存放device(cpu/gpu)。

In [3]:
x = torch.Tensor(2,4)
print(x)

tensor([[3.1725e+32, 4.5422e-41, 3.1725e+32, 4.5422e-41],
        [7.0118e-25, 3.2027e-41, 7.0118e-25, 3.2027e-41]])


In [8]:
x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

# x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
# print(x)

y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# adds x to y
y.add_(x)
print(y)




tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1.9134, 1.5444, 1.5629],
        [1.4416, 1.1371, 1.4866],
        [1.0599, 1.8381, 1.9252],
        [1.7050, 1.7274, 1.5683],
        [1.3492, 1.6116, 1.9756]], dtype=torch.float64)
tensor([[1.9134, 1.5444, 1.5629],
        [1.4416, 1.1371, 1.4866],
        [1.0599, 1.8381, 1.9252],
        [1.7050, 1.7274, 1.5683],
        [1.3492, 1.6116, 1.9756]], dtype=torch.float64)
tensor([[1.9134, 1.5444, 1.5629],
        [1.4416, 1.1371, 1.4866],
        [1.0599, 1.8381, 1.9252],
        [1.7050, 1.7274, 1.5683],
        [1.3492, 1.6116, 1.9756]])
tensor([[1.9134, 1.5444, 1.5629],
        [1.4416, 1.1371, 1.4866],
        [1.0599, 1.8381, 1.9252],
        [1.7050, 1.7274, 1.5683],
        [1.3492, 1.6116, 1.9756]])


In [9]:
# 索引
# 我们还可以使用类似NumPy的索引操作来访问Tensor的一部分，需要注意的是：索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。

y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了


tensor([2., 2., 2.], dtype=torch.float64)
tensor([2., 2., 2.], dtype=torch.float64)


In [14]:
# 改变形状
# 用view()来改变Tensor的形状：
print(x)

y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

# 注意view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)
x += 1
print(x)
print(y) # 也加了1

# 所以如果我们想返回一个真正新的副本（即不共享data内存）该怎么办呢？Pytorch还提供了一个reshape()可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先用clone创造一个副本然后再使用view。
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

# 使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor。

# 另外一个常用的函数就是item(), 它可以将一个标量Tensor转换成一个Python number：
x = torch.randn(1)
print(x)
print(x.item())



tensor([[4., 4., 4.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64)
torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])
tensor([[5., 5., 5.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]], dtype=torch.float64)
tensor([5., 5., 5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       dtype=torch.float64)
tensor([[4., 4., 4.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64)
tensor([5., 5., 5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       dtype=torch.float64)
tensor([0.3868])
0.3867504596710205


线性代数

另外，PyTorch还支持一些线性函数，这里提一下，免得用起来的时候自己造轮子，具体用法参考官方文档。如下表所示：


trace	对角线元素之和(矩阵的迹)

diag	对角线元素
triu/tril	矩阵的上三角/下三角，可指定偏移量

mm/bmm	矩阵乘法，batch的矩阵乘法

addmm/addbmm/addmv/addr/baddbmm..	矩阵运算

t	转置

dot/cross	内积/外积

inverse	求逆矩阵

svd	奇异值分解

PyTorch中的Tensor支持超过一百种操作，包括转置、索引、切片、数学运算、线性代数、随机数等等，可参考官方文档。

In [3]:
# 广播机制
# 前面我们看到如何对两个形状相同的Tensor做按元素运算。当对两个形状不同的Tensor按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个Tensor形状相同后再按元素运算。例如：

x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [10]:
# 运算的内存开销

# 前面说了，索引操作是不会开辟新内存的，而像y = x + y这样的运算是会新开内存的，然后将y指向新内存。为了演示这一点，我们可以使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
print(id_before)
y = y + x
print(y)
print(id(y))
print(id(y) == id_before) # False


x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(y)
print(id(y) == id_before) # True

# 我们还可以使用运算符全名函数中的out参数或者自加运算符+=(也即add_())达到上述效果，例如torch.add(x, y, out=y)和y += x(y.add_(x))。
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before) # True

# 注：虽然view返回的Tensor与源Tensor是共享data的，但是依然是一个新的Tensor（因为Tensor除了包含data外还有一些其他属性），二者id（内存地址）并不一致。

135221121705568
tensor([4, 6])
135221121705648
False
tensor([4, 6])
True
True


In [13]:
# Tensor和NumPy相互转换
# 我们很容易用numpy()和from_numpy()将Tensor和NumPy中的数组相互转换。但是需要注意的一点是： 这两个函数所产生的的Tensor和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！

# 还有一个常用的将NumPy中的array转换成Tensor的方法就是torch.tensor(), 需要注意的是，此方法总是会进行数据拷贝（就会消耗更多的时间和空间），所以返回的Tensor和原来的数据不再共享内存。

# Tensor转NumPy
# 使用numpy()将Tensor转换成NumPy数组:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

# NumPy数组转Tensor
# 使用from_numpy()将NumPy数组转换成Tensor:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

# 所有在CPU上的Tensor（除了CharTensor）都支持与NumPy数组相互转换。

# 此外上面提到还有一个常用的方法就是直接用torch.tensor()将NumPy数组转换成Tensor，需要注意的是该方法总是会进行数据拷贝，返回的Tensor和原来的数据不再共享内存。
c = torch.tensor(a)
a += 1
print(a, c)


tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]
[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [20]:
# Tensor on GPU
# 用方法to()可以将Tensor在CPU和GPU（需要硬件支持）之间相互移动。
# print(x)

# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    # print(x)
    # print(y)
    x = x.to(device)                       # 等价于 .to("cuda")
    # print(x)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型


tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)
